# Use the official .NET SDK image to build the app
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy and restore the referenced project
COPY CoreLibrary/CoreLibrary.csproj CoreLibrary/
RUN dotnet restore CoreLibrary/CoreLibrary.csproj

# Copy the project files and restore dependencies
COPY WebApplication1.User/WebApplication1.User.csproj WebApplication1.User/
RUN dotnet restore WebApplication1.User/WebApplication1.User.csproj

# Copy the remaining files and build the app
COPY . .
WORKDIR /src/WebApplication1.User
RUN dotnet publish -c Release -o /app/publish

# Use the official ASP.NET Core runtime image to run the app
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .

# Copy the appsettings.json file
COPY WebApplication1.User/appsettings.json .

# Copy the certificate and set environment variables
ENV ASPNETCORE_Kestrel__Certificates__Default__Password=qw@rty123
ENV ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certificate.pfx

# Expose the port your gRPC service is listening on
EXPOSE 5250
EXPOSE 7017

# Run the app
ENTRYPOINT ["dotnet", "WebApplication1.User.dll"]