# Use the official .NET SDK image to build the app
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy and restore the referenced project
COPY CoreLibrary/CoreLibrary.csproj CoreLibrary/
RUN dotnet restore CoreLibrary/CoreLibrary.csproj

# Copy the project files and restore dependencies
COPY WebApplication1.Admin/WebApplication1.Admin.csproj WebApplication1.Admin/
RUN dotnet restore WebApplication1.Admin/WebApplication1.Admin.csproj

# Copy the remaining files and build the app
COPY . .
WORKDIR /src/WebApplication1.Admin
RUN dotnet publish -c Release -o /app/publish

# Use the official ASP.NET Core runtime image to run the app
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .

# Copy the appsettings.json file
COPY WebApplication1.Admin/appsettings.json .

COPY ./certs/certificate.pfx /app/aspnetcore-dev-cert.pfx
ENV ASPNETCORE_Kestrel__Certificates__Default__Password=qw@rty123
ENV ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certificate.pfx

# Expose the port your gRPC service is listening on
EXPOSE 5071
EXPOSE 7272

# Run the app
ENTRYPOINT ["dotnet", "WebApplication1.Admin.dll"]