# Use the official .NET SDK image to build the app
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy and restore the referenced project
COPY CoreLibrary/CoreLibrary.csproj CoreLibrary/
RUN dotnet restore CoreLibrary/CoreLibrary.csproj

# Copy the project files and restore dependencies
COPY WebApplication1.Gateway/WebApplication1.Gateway.csproj WebApplication1.Gateway/
RUN dotnet restore WebApplication1.Gateway/WebApplication1.Gateway.csproj

# Copy the remaining files and build the app
COPY . .
WORKDIR /src/WebApplication1.Gateway
RUN dotnet publish -c Release -o /app/publish

# Use the official ASP.NET Core runtime image to run the app
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .

# Copy the appsettings.json file
COPY WebApplication1.Gateway/appsettings.json .

# Expose the port gateway is listening on
EXPOSE 5210

# Run the app
ENTRYPOINT ["dotnet", "WebApplication1.Gateway.dll"]