services:
  redis:
    image: redis:latest
    container_name: myredis
    networks:
      - net-webapi01_default
    ports:
      - "6379:6379"

  usergrpcservice:
    image: localhost:5000/usergrpcservice:latest
    build:
      context: .
      dockerfile: ./Dockerfile_grpc_user
    volumes:
      - ./certs/certificate.pfx:/app/certificate.pfx
      - usergrpcservice-data:/app/data
    ports:
      - "7018:7018"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - net-webapi01_default

  admingrpcservice:
    image: localhost:5000/admingrpcservice:latest
    build:
      context: .
      dockerfile: ./Dockerfile_grpc_admin
    volumes:
      - ./certs/certificate.pfx:/app/certificate.pfx
    ports:
      - "7275:7275"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - net-webapi01_default

  bookgateway:
    image: localhost:5000/bookgateway:latest
    build:
      context: .
      dockerfile: ./Dockerfile_gw
    volumes:
      - ./certs/cert.pem:/app/cert.pem
      - bookgateway-data:/app/data
    ports:
      - "5210:5210"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - usergrpcservice
      - admingrpcservice
    networks:
      - net-webapi01_default

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=ytr@wq321
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - net-webapi01_default

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_user
      - ELASTICSEARCH_PASSWORD=kibana_password
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - net-webapi01_default

volumes:
  usergrpcservice-data:
  bookgateway-data:
  elasticsearch-data:

networks:
  net-webapi01_default:
